# Generated by Django 5.2.7 on 2025-10-07 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du coin CinéBar', max_length=100)),
                ('slogan', models.CharField(blank=True, help_text='Petit slogan amusant', max_length=150)),
                ('drink_of_the_day', models.CharField(blank=True, help_text='Boisson du moment (ex: Mojito, Margarita)', max_length=100)),
                ('happy_hour_start', models.TimeField(blank=True, null=True)),
                ('happy_hour_end', models.TimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('movie', models.ForeignKey(help_text='Film associé à ce coin bar', on_delete=django.db.models.deletion.CASCADE, related_name='cinebars', to='movies.movie')),
            ],
        ),
    ]
